CREATE EXTERNAL TABLE `voyager_lake.events`(
  `global_event_id` string, 
  `sqldate` date, 
  `month_year` string, 
  `year` string, 
  `fraction_date` string, 
  `actor_1_code` string, 
  `actor_1_name` string, 
  `actor_1_country_code` string, 
  `actor_1_known_group_code` string, 
  `actor_1_ethnic_code` string, 
  `actor_1_religion_code` string, 
  `actor_1_religion_2_code` string, 
  `actor_1_type_code` string, 
  `actor_1_type_2_code` string, 
  `actor_1_type_3_code` string, 
  `actor_2_code` string, 
  `actor_name` string, 
  `actor_2_country_code` string, 
  `actor_2_known_group_code` string, 
  `actor_2_ethnic_code` string, 
  `actor_2_religion_1_code` string, 
  `actor_2_religion_2_code` string, 
  `actor_2_type_1_code` string, 
  `actor_2_type_2_code` string, 
  `actor_2_type_3_code` string, 
  `is_root_event` string, 
  `event_code` string, 
  `event_base_code` string, 
  `event_root_code` string, 
  `quad_class` string, 
  `goldstein_scale` string, 
  `num_mentions` string, 
  `num_sources` string, 
  `num_articles` string, 
  `avg_tone` string, 
  `actor_1_geo_type` string, 
  `actor_1_geo_fullname` string, 
  `actor_1_geo_country_code` string, 
  `actor_1_geo_adm1_code` string, 
  `actor_1_geo_lat` string, 
  `actor_1_geo_long` string, 
  `actor_1_geo_feature_id` string, 
  `actor_2_geo_type` string, 
  `actor_2_geo_fullname` string, 
  `actor_2_geo_country_code` string, 
  `actor_2_geo_adm1_code` string, 
  `actor_2_geo_lat` string, 
  `actor_2_geo_long` string, 
  `actor_2_geo_feature_id` string, 
  `action_geo_type` string, 
  `action_geo_fullname` string, 
  `action_geo_country_code` string, 
  `action_geo_adm1_code` string, 
  `action_geo_lat` string, 
  `action_geo_long` string, 
  `action_geo_feature_id` string, 
  `source_url` string, 
  `actor_1_geo_feature_id_num` string, 
  `actor_1_geo_feature_id_text` string, 
  `actor_2_geo_feature_id_num` string, 
  `actor_2_geo_feature_id_text` string)
PARTITIONED BY ( 
  `date_added` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://factored-datathon-2024-voyager/parquet/events/'
TBLPROPERTIES (
  'CrawlerSchemaDeserializerVersion'='1.0', 
  'CrawlerSchemaSerializerVersion'='1.0', 
  'UPDATED_BY_CRAWLER'='event_data', 
  'averageRecordSize'='192', 
  'classification'='parquet', 
  'compressionType'='none', 
  'objectCount'='6000', 
  'partition_filtering.enabled'='true', 
  'recordCount'='48562397', 
  'sizeKey'='6754188186', 
  'typeOfData'='file')